// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/akari_client.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 737333047;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_akari_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  BigInt crateApiAkariClientAkariClientPoolActiveCount({
    required AkariClientPool that,
  });

  Future<AkariClientPool> crateApiAkariClientAkariClientPoolNew({
    required String host,
    required int port,
    required List<int> psk,
    required BigInt poolSize,
  });

  BigInt crateApiAkariClientAkariClientPoolPoolSize({
    required AkariClientPool that,
  });

  Future<AkariHttpResponse> crateApiAkariClientAkariClientPoolSendRequest({
    required AkariClientPool that,
    required String url,
    required AkariRequestConfig config,
  });

  Future<AkariHttpResponse>
  crateApiAkariClientAkariClientPoolSendRequestWithMethod({
    required AkariClientPool that,
    required String url,
    required String method,
    required AkariRequestConfig config,
  });

  Future<AkariClient> crateApiAkariClientAkariClientNew({
    required String host,
    required int port,
    required List<int> psk,
  });

  Future<AkariHttpResponse> crateApiAkariClientAkariClientSendRequest({
    required AkariClient that,
    required String url,
    required AkariRequestConfig config,
  });

  Future<AkariHttpResponse>
  crateApiAkariClientAkariClientSendRequestWithMethod({
    required AkariClient that,
    required String url,
    required String method,
    required AkariRequestConfig config,
  });

  Future<AkariRequestConfig> crateApiAkariClientAkariRequestConfigDefault();

  AkariRequestConfig crateApiAkariClientDefaultRequestConfig();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AkariClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AkariClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AkariClientPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AkariClientPool;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AkariClientPool;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AkariClientPoolPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  BigInt crateApiAkariClientAkariClientPoolActiveCount({
    required AkariClientPool that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAkariClientAkariClientPoolActiveCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientPoolActiveCountConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClientPool_active_count",
        argNames: ["that"],
      );

  @override
  Future<AkariClientPool> crateApiAkariClientAkariClientPoolNew({
    required String host,
    required int port,
    required List<int> psk,
    required BigInt poolSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_list_prim_u_8_loose(psk, serializer);
          sse_encode_usize(poolSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAkariClientAkariClientPoolNewConstMeta,
        argValues: [host, port, psk, poolSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientPoolNewConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClientPool_new",
        argNames: ["host", "port", "psk", "poolSize"],
      );

  @override
  BigInt crateApiAkariClientAkariClientPoolPoolSize({
    required AkariClientPool that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAkariClientAkariClientPoolPoolSizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientPoolPoolSizeConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClientPool_pool_size",
        argNames: ["that"],
      );

  @override
  Future<AkariHttpResponse> crateApiAkariClientAkariClientPoolSendRequest({
    required AkariClientPool that,
    required String url,
    required AkariRequestConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_box_autoadd_akari_request_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_http_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAkariClientAkariClientPoolSendRequestConstMeta,
        argValues: [that, url, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientPoolSendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClientPool_send_request",
        argNames: ["that", "url", "config"],
      );

  @override
  Future<AkariHttpResponse>
  crateApiAkariClientAkariClientPoolSendRequestWithMethod({
    required AkariClientPool that,
    required String url,
    required String method,
    required AkariRequestConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_String(method, serializer);
          sse_encode_box_autoadd_akari_request_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_http_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiAkariClientAkariClientPoolSendRequestWithMethodConstMeta,
        argValues: [that, url, method, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAkariClientAkariClientPoolSendRequestWithMethodConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClientPool_send_request_with_method",
        argNames: ["that", "url", "method", "config"],
      );

  @override
  Future<AkariClient> crateApiAkariClientAkariClientNew({
    required String host,
    required int port,
    required List<int> psk,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_list_prim_u_8_loose(psk, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAkariClientAkariClientNewConstMeta,
        argValues: [host, port, psk],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClient_new",
        argNames: ["host", "port", "psk"],
      );

  @override
  Future<AkariHttpResponse> crateApiAkariClientAkariClientSendRequest({
    required AkariClient that,
    required String url,
    required AkariRequestConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_box_autoadd_akari_request_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_http_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAkariClientAkariClientSendRequestConstMeta,
        argValues: [that, url, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariClientSendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClient_send_request",
        argNames: ["that", "url", "config"],
      );

  @override
  Future<AkariHttpResponse>
  crateApiAkariClientAkariClientSendRequestWithMethod({
    required AkariClient that,
    required String url,
    required String method,
    required AkariRequestConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_String(method, serializer);
          sse_encode_box_autoadd_akari_request_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_http_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiAkariClientAkariClientSendRequestWithMethodConstMeta,
        argValues: [that, url, method, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAkariClientAkariClientSendRequestWithMethodConstMeta =>
      const TaskConstMeta(
        debugName: "AkariClient_send_request_with_method",
        argNames: ["that", "url", "method", "config"],
      );

  @override
  Future<AkariRequestConfig> crateApiAkariClientAkariRequestConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_request_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAkariClientAkariRequestConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientAkariRequestConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "akari_request_config_default",
        argNames: [],
      );

  @override
  AkariRequestConfig crateApiAkariClientDefaultRequestConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_akari_request_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAkariClientDefaultRequestConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAkariClientDefaultRequestConfigConstMeta =>
      const TaskConstMeta(debugName: "default_request_config", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AkariClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AkariClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AkariClientPool => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AkariClientPool => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool;

  @protected
  AkariClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AkariClientPool
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AkariClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AkariClientPool
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AkariClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AkariClientPool
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AkariHttpResponse dco_decode_akari_http_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AkariHttpResponse(
      statusCode: dco_decode_u_16(arr[0]),
      headers: dco_decode_list_record_string_string(arr[1]),
      body: dco_decode_list_prim_u_8_strict(arr[2]),
      stats: dco_decode_akari_transfer_stats(arr[3]),
    );
  }

  @protected
  AkariRequestConfig dco_decode_akari_request_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AkariRequestConfig(
      timeoutMs: dco_decode_u_64(arr[0]),
      maxNackRounds: dco_decode_opt_box_autoadd_u_32(arr[1]),
      initialRequestRetries: dco_decode_u_32(arr[2]),
      sockTimeoutMs: dco_decode_u_64(arr[3]),
      firstSeqTimeoutMs: dco_decode_u_64(arr[4]),
      aggTag: dco_decode_bool(arr[5]),
      shortId: dco_decode_bool(arr[6]),
    );
  }

  @protected
  AkariTransferStats dco_decode_akari_transfer_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AkariTransferStats(
      bytesSent: dco_decode_u_64(arr[0]),
      bytesReceived: dco_decode_u_64(arr[1]),
      nacksSent: dco_decode_u_32(arr[2]),
      requestRetries: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AkariRequestConfig dco_decode_box_autoadd_akari_request_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_akari_request_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AkariClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AkariClientPool
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AkariClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AkariClientPool
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AkariClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AkariClientPool
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AkariClientPoolImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AkariHttpResponse sse_decode_akari_http_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_statusCode = sse_decode_u_16(deserializer);
    var var_headers = sse_decode_list_record_string_string(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stats = sse_decode_akari_transfer_stats(deserializer);
    return AkariHttpResponse(
      statusCode: var_statusCode,
      headers: var_headers,
      body: var_body,
      stats: var_stats,
    );
  }

  @protected
  AkariRequestConfig sse_decode_akari_request_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeoutMs = sse_decode_u_64(deserializer);
    var var_maxNackRounds = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_initialRequestRetries = sse_decode_u_32(deserializer);
    var var_sockTimeoutMs = sse_decode_u_64(deserializer);
    var var_firstSeqTimeoutMs = sse_decode_u_64(deserializer);
    var var_aggTag = sse_decode_bool(deserializer);
    var var_shortId = sse_decode_bool(deserializer);
    return AkariRequestConfig(
      timeoutMs: var_timeoutMs,
      maxNackRounds: var_maxNackRounds,
      initialRequestRetries: var_initialRequestRetries,
      sockTimeoutMs: var_sockTimeoutMs,
      firstSeqTimeoutMs: var_firstSeqTimeoutMs,
      aggTag: var_aggTag,
      shortId: var_shortId,
    );
  }

  @protected
  AkariTransferStats sse_decode_akari_transfer_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_bytesReceived = sse_decode_u_64(deserializer);
    var var_nacksSent = sse_decode_u_32(deserializer);
    var var_requestRetries = sse_decode_u_32(deserializer);
    return AkariTransferStats(
      bytesSent: var_bytesSent,
      bytesReceived: var_bytesReceived,
      nacksSent: var_nacksSent,
      requestRetries: var_requestRetries,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AkariRequestConfig sse_decode_box_autoadd_akari_request_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_akari_request_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    AkariClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    AkariClientPool self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientPoolImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    AkariClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    AkariClientPool self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientPoolImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClient(
    AkariClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAkariClientPool(
    AkariClientPool self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AkariClientPoolImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_akari_http_response(
    AkariHttpResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.statusCode, serializer);
    sse_encode_list_record_string_string(self.headers, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
    sse_encode_akari_transfer_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_akari_request_config(
    AkariRequestConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timeoutMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxNackRounds, serializer);
    sse_encode_u_32(self.initialRequestRetries, serializer);
    sse_encode_u_64(self.sockTimeoutMs, serializer);
    sse_encode_u_64(self.firstSeqTimeoutMs, serializer);
    sse_encode_bool(self.aggTag, serializer);
    sse_encode_bool(self.shortId, serializer);
  }

  @protected
  void sse_encode_akari_transfer_stats(
    AkariTransferStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_u_64(self.bytesReceived, serializer);
    sse_encode_u_32(self.nacksSent, serializer);
    sse_encode_u_32(self.requestRetries, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_akari_request_config(
    AkariRequestConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_akari_request_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class AkariClientImpl extends RustOpaque implements AkariClient {
  // Not to be used by end users
  AkariClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AkariClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AkariClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AkariClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AkariClientPtr,
  );

  /// Send an HTTP GET request and return the response.
  Future<AkariHttpResponse> sendRequest({
    required String url,
    required AkariRequestConfig config,
  }) => RustLib.instance.api.crateApiAkariClientAkariClientSendRequest(
    that: this,
    url: url,
    config: config,
  );

  /// Send an HTTP request with specified method.
  Future<AkariHttpResponse> sendRequestWithMethod({
    required String url,
    required String method,
    required AkariRequestConfig config,
  }) =>
      RustLib.instance.api.crateApiAkariClientAkariClientSendRequestWithMethod(
        that: this,
        url: url,
        method: method,
        config: config,
      );
}

@sealed
class AkariClientPoolImpl extends RustOpaque implements AkariClientPool {
  // Not to be used by end users
  AkariClientPoolImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AkariClientPoolImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AkariClientPool,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AkariClientPool,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AkariClientPoolPtr,
  );

  /// Get the current number of active clients.
  BigInt activeCount() => RustLib.instance.api
      .crateApiAkariClientAkariClientPoolActiveCount(that: this);

  /// Get the pool size (maximum number of concurrent clients).
  BigInt poolSize() => RustLib.instance.api
      .crateApiAkariClientAkariClientPoolPoolSize(that: this);

  /// Send an HTTP GET request and return the response.
  ///
  /// This method acquires a client from the pool, sends the request,
  /// and releases the client back to the pool.
  Future<AkariHttpResponse> sendRequest({
    required String url,
    required AkariRequestConfig config,
  }) => RustLib.instance.api.crateApiAkariClientAkariClientPoolSendRequest(
    that: this,
    url: url,
    config: config,
  );

  /// Send an HTTP request with specified method.
  Future<AkariHttpResponse> sendRequestWithMethod({
    required String url,
    required String method,
    required AkariRequestConfig config,
  }) => RustLib.instance.api
      .crateApiAkariClientAkariClientPoolSendRequestWithMethod(
        that: this,
        url: url,
        method: method,
        config: config,
      );
}
